### ISSUE TITLE
Shutter blinds position at HA reboot

### ISSUE THREAD

**Issue by jokerigno** [stefanbode/Sonoff-Tasmota#131]
I'm using your fork to manage my shutter blinds and everything is ok. 

The only "issue" is that if i Reboot my Home Assistant I can't see shutter position anymore.

There's a way to fix it?

Here's my code for covers in HA:

```
cover:
  - platform: mqtt
    name: "Tapparella"
    availability_topic: "tapparellatele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    position_topic: "tapparella/stat/SHUTTER1"
    position_open: 100
    position_closed: 0
    set_position_topic: "tapparella/cmnd/shutterposition"
    value_template: "{{ value | int }}"
    command_topic: "tapparella/cmnd/backlog"
    payload_open: "SHUTTEROPEN"
    payload_close: "SHUTTERCLOSE"
    payload_stop: "SHUTTERSTOP"
    retain: false
    optimistic: false
    qos: 0
```
